# /* ==================================================================================== */
# /*     Copyright (c) 2016-2021 QUALCOMM Technologies, Inc. and/or its subsidiaries.     */
# /*                           All Rights Reserved.                                       */
# /*                  QUALCOMM Confidential and Proprietary                               */
# /* ==================================================================================== */

CURR_DIR = $(shell pwd)
SIMULATOR_STANDALONE_TOP_DIR = $(CURR_DIR)/../../
TESTNAME = $(shell basename $(CURR_DIR))

include $(SIMULATOR_STANDALONE_TOP_DIR)/apps/Makefile.common

include $(SIMULATOR_STANDALONE_TOP_DIR)/apps/Makefile.rules
