/**=============================================================================
Copyright (c) 2020 QUALCOMM Technologies Incorporated.
All Rights Reserved Qualcomm Proprietary
=============================================================================**/

/*
 * @file            hap_unit_test.c
 *
 * @services        Valdates all the HAP APIs that can be validated
 *
 * @description     Unit tests are written by comparing the output generated by the HAP API
 *                  with an expected output that is generated by another HAP API,
 *                  remote_handle APIs or rpcmem APIs
 */

#include "hap_example.h"

#include <stdlib.h>
#include <stdio.h>
#include <sys/types.h>
#include <sys/stat.h>
#include <fcntl.h>
#include <inttypes.h>

/*Header file for FastRPC APIs and macros*/
#include <remote.h>

/*Header file for ION memory allocation APIs*/
#include <rpcmem.h>

/*Header file for Standard Error Codes returned by QuRT*/
#include "AEEStdErr.h"


#define BUF_LEN 4096
#define ARRAY_LEN 1024


int hap_unit_test(void)
{
    int retVal = 0;
    int i;

    remote_handle64 handle = -1;

    /*
     * We run the example on CDSP by default
     */
    char *hap_example_URI_domain = hap_example_URI "&_dom=cdsp";
    retVal = hap_example_open(hap_example_URI_domain, &handle);

    if(retVal!=0)
    {
        printf("Error Code: 0x%x - Unable to create FastRPC session on CDSP\n", retVal);
        goto bail;
    }


    /*
     * For validating HAP_mmap, we create initialize an ION buffer from the APPS processor and verify its values from the DSP
     */
    unsigned int* ion_buffer = (unsigned int*) rpcmem_alloc(RPCMEM_HEAP_ID_SYSTEM, RPCMEM_DEFAULT_FLAGS, BUF_LEN);

    if(ion_buffer==NULL)
    {
        printf("Failed to allocate ION memory\n");
        retVal = -1;
        goto handle_close;
    }

    int fd = rpcmem_to_fd((void*)ion_buffer);

    for (i = 0; i < ARRAY_LEN; ++i)
    {
        ion_buffer[i] = i;
    }

    retVal = hap_example_unit_test(handle, fd, 0, BUF_LEN);

handle_close:
    hap_example_close(handle);
bail:

    if(retVal==AEE_SUCCESS)
    {
        printf("\nhap_unit_test PASSED\n");
    }
    else
    {
        printf("\nhap_unit_test FAILED\n");
    }

    return retVal;
}
